#pragma once

enum class ChefStatesEnum {
    WAITING_TO_START,
    COOKING,
    TURNING_RIGHT,
    MOVING_RIGHT,
    PREPARING_TO_PUTTING_DOWN,
    PUTTING_DOWN,
    TURNING_LEFT,
    MOVING_LEFT,
    TURNING_UP,
    TURNING_DOWN,
    PREPARING_TO_COOKING
};