#pragma once

enum CustomerStatesEnum {
    WAITING_TO_START,
    PREPARING_TO_MOVE,
    MOVING_LEFT,
    WAITING_TO_MOVE,
    TURNING_UP,
    MOVING_UP,
    WAITING_TO_ENTER,
    TURNING_DOWN,
    MOVING_DOWN,
    TURNING_RIGHT,
    MOVING_RIGHT,
    WAITING_TO_REMOVE,
    PREPARING_TO_ENTER_RESTAURANT,
    ENTER_TO_RESTAURANT,
    PREPARING_TO_MOVE_TO_CHAIR,
    MOVING_TO_CHAIR,
    PREPARING_TO_SIT,
    NO_MOVEMENT,
    SITTING
};